### ISSUE TITLE
Add button to enable adding a case

### ISSUE THREAD

**Issue by hanseljt77** [RoseContactTracer/covid-tracer-frontend#13]
Health services needs to be able to add a positive case through the frontend.

Acceptance Criteria:

- [x] Button for adding a case on the person profile
- [x] Opens a dialog asking for the test date
- [x] New case appears in the frontend as well as the db

**Comment by meistejw** [comment]
Most of the functionality is there. We just need to add a dialogue box for adding info to the case.
