### ISSUE TITLE
Create Positive Case View

### ISSUE THREAD

**Issue by hanseljt77** [RoseContactTracer/covid-tracer-frontend#4]
As a developer I want to be able to see a list of positive cases displayed on the front end

Acceptance Criteria:
- [x] Positive case view shown containing hardcoded data

**Comment by meistejw** [comment]
Should have closed with the PR.

**Comment by DRSisco** [comment]
So GitHub takes only the first reference after the keyword. So if you wanted to close all those issues you needed to do:
```
closes #3 
closes #4
closes #5
```
I mean you did reference them all, which is good (I have been intentionally tossing my examples in code blocks to avoid referencing). But yeah need one keyword per issue reference.
